name: deploy to ECS cluster.
on: 
 push:
   branches:
     - main
  
jobs:
 deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: check path
        run: ls -la && pwd 
